M48
; DRILL file {KiCad 9.0.4} date 2025-10-26T21:25:07+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-10-26T21:25:07+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.750
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
%
G90
G05
T1
X152.7Y81.1
X152.7Y75.3
T2
X3.2Y94.45
X3.57Y5.55
X157.24Y94.45
X157.24Y5.55
M30
